## NOTE: dont put comments immediately after a key:string, comments will be interpreted as '\t'; also, usespace key instead of \TAB for ANY spacing!! (yaml-cpp is still buggy for parsing)

slam:
  num_particles: 1
  initial_w: 1.0
  motion_noise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  measurement_noise: [0.1, 0.1]